### ISSUE TITLE
Not able to create a table in hbase

### ISSUE THREAD

**Issue by Chandanap99** [hortonworks/shc#21]
Hi,

I am not able to create a table as it is not able to connect to my cluster using zookeeper.

> 16/08/08 12:30:13 INFO ClientCnxn: Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
16/08/08 12:30:13 WARN RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
16/08/08 12:30:13 WARN ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

Could you please tell me where can I put/configure my hbase-site.xml and core-site.xml. 

Thanks

**Comment by joyparkko** [comment]
That is because configuration cannot be loaded, and adding them manually might help you to solve the problem.
try to add 
```
      hbaseConf.set("zookeeper.znode.parent", "/hbase-secure")
      hbaseConf.set("hbase.zookeeper.quorum","{zookeeper.quorum}")
      hbaseConf.set("hbase.zookeeper.property.clientPort","2181")
```

**Comment by nicodv** [comment]
I'm having the same problem, but running from PySpark. Is there another way to solve this?

**Comment by adamdec** [comment]
If you run integration tests on Hadoop Mini Cluster using HBaseTestingUtility, consider setting the property:
test.hbase.zookeeper.property.clientPort to "2181"

http://stackoverflow.com/questions/32752513/hbasetestingutility-set-configuration-zookeeper-clientport-not-working
